# Generated by Django 5.0.6 on 2024-06-25 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='something', max_length=100)),
                ('type', models.CharField(choices=[('Egreso', 'Egreso'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('qty', models.BigIntegerField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Category', models.CharField(choices=[('Comida', 'Comida'), ('Transporte', 'Transporte'), ('Compras', 'Compras'), ('Servicios', 'Servicios'), ('Entretenimiento', 'Entretenimiento'), ('Otro', 'Otro')], default='', max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
