# Generated by Django 5.0.6 on 2024-06-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='qty',
            field=models.BigIntegerField(default=0),
        ),
    ]
