# Generated by Django 5.0.6 on 2024-07-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_expense_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='Category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Egreso', 'Egreso'), ('Ingreso', 'Ingreso')], default='Egreso', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Transporte', 'Transporte'), ('Compras', 'Compras'), ('Servicios', 'Servicios'), ('Entretenimiento', 'Entretenimiento'), ('Otro', 'Otro')], default='Comida', max_length=20),
        ),
    ]
